/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public String getGreeting() {
    return "こんにちは SEMonster";
  }

  public String gameStartMessage() {
    return "Game Start!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    System.out.println(new App().gameStartMessage());

    // Monsterクラス
    Monster monster = new Monster(0);
    monster.toString();
  }
}
